//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF_new.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JofriendEntities : DbContext
    {
        public JofriendEntities()
            : base("name=JofriendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityDetail> ActivityDetail { get; set; }
        public virtual DbSet<Blacklist> Blacklist { get; set; }
        public virtual DbSet<Chatroom> Chatroom { get; set; }
        public virtual DbSet<Exchange> Exchange { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<Follow> Follow { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MessageDetail> MessageDetail { get; set; }
        public virtual DbSet<Preference> Preference { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<RobotDictionary> RobotDictionary { get; set; }
        public virtual DbSet<RobotRecord> RobotRecord { get; set; }
        public virtual DbSet<Suggest> Suggest { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Category> Category { get; set; }
    }
}
