//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> AddedTime { get; set; }
        public Nullable<System.DateTime> ShelfTime { get; set; }
        public Nullable<int> Token { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
