//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int userID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public string imgUrl { get; set; }
        public string intro { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> registerMode { get; set; }
        public Nullable<int> status { get; set; }
    }
}
