USE [master]
GO
/****** Object:  Database [TestAPI]    Script Date: 2017/11/29 下午 11:46:10 ******/
CREATE DATABASE [TestAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TestAPI.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TestAPI_log.ldf' , SIZE = 1600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TestAPI] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestAPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TestAPI] SET  MULTI_USER 
GO
ALTER DATABASE [TestAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestAPI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TestAPI] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TestAPI', N'ON'
GO
USE [TestAPI]
GO
/****** Object:  User [IIS APPPOOL\DefaultAppPool]    Script Date: 2017/11/29 下午 11:46:10 ******/
CREATE USER [IIS APPPOOL\DefaultAppPool] FOR LOGIN [IIS APPPOOL\DefaultAppPool] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_datareader] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [IIS APPPOOL\DefaultAppPool]
GO
/****** Object:  Table [dbo].[admin]    Script Date: 2017/11/29 下午 11:46:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[admin](
	[adminID] [int] IDENTITY(1,1) NOT NULL,
	[account] [nvarchar](50) NULL,
	[password] [nvarchar](max) NULL,
	[status] [int] NULL CONSTRAINT [DF_admin_status]  DEFAULT ((0)),
	[authority] [int] NULL CONSTRAINT [DF_admin_authority]  DEFAULT ((1)),
	[remember_token] [nvarchar](max) NULL,
	[createAt] [datetime] NULL CONSTRAINT [DF_admin_createAt]  DEFAULT (getdate()),
	[updateAt] [datetime] NULL CONSTRAINT [DF_admin_updateAt]  DEFAULT (getdate()),
 CONSTRAINT [PK_admin] PRIMARY KEY CLUSTERED 
(
	[adminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[product]    Script Date: 2017/11/29 下午 11:46:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[category] [varchar](50) NULL,
	[price] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [TestAPI] SET  READ_WRITE 
GO
